### ISSUE TITLE
Maybe some typos in the code

### ISSUE THREAD

**Issue by yaoyic** [peastman/openmm-torch#2]
Hi Peter,

during my compiling the code on the 3rd commit, I found something preventing the `make` process:
For file `platforms/reference/src/ReferenceNeuralNetworkKernels.cpp`:
```
[ 39%] Building CXX object platforms/reference/CMakeFiles/OpenMMNNReference.dir/src/ReferenceNeuralNetworkKernels.cpp.o
/srv/public/yaoyic/openmm-torch/platforms/reference/src/ReferenceNeuralNetworkKernels.cpp: In function ‘std::vector<OpenMM::Vec3>& extractPositions(OpenMM::ContextImpl&)’:
/srv/public/yaoyic/openmm-torch/platforms/reference/src/ReferenceNeuralNetworkKernels.cpp:44:19: error: ‘void*’ is not a pointer-to-object type
     return *data->positions;
                   ^~~~~~~~~
/srv/public/yaoyic/openmm-torch/platforms/reference/src/ReferenceNeuralNetworkKernels.cpp: In function ‘std::vector<OpenMM::Vec3>& extractForces(OpenMM::ContextImpl&)’:
/srv/public/yaoyic/openmm-torch/platforms/reference/src/ReferenceNeuralNetworkKernels.cpp:49:19: error: ‘void*’ is not a pointer-to-object type
     return *data->forces;
                   ^~~~~~
/srv/public/yaoyic/openmm-torch/platforms/reference/src/ReferenceNeuralNetworkKernels.cpp: In function ‘OpenMM::Vec3* extractBoxVectors(OpenMM::ContextImpl&)’:
/srv/public/yaoyic/openmm-torch/platforms/reference/src/ReferenceNeuralNetworkKernels.cpp:54:18: error: invalid conversion from ‘void*’ to ‘OpenMM::Vec3*’ [-fpermissive]
     return data->periodicBoxVectors;
            ~~~~~~^~~~~~~~~~~~~~~~~~
platforms/reference/CMakeFiles/OpenMMNNReference.dir/build.make:75: die Regel für Ziel „platforms/reference/CMakeFiles/OpenMMNNReference.dir/src/ReferenceNeuralNetworkKernels.cpp.o“ scheiterte
make[2]: *** [platforms/reference/CMakeFiles/OpenMMNNReference.dir/src/ReferenceNeuralNetworkKernels.cpp.o] Fehler 1
```
After comparing to the counter part in the TF plugin, I guess here it should be changed into:
```C++
static vector<Vec3>& extractPositions(ContextImpl& context) {
    ReferencePlatform::PlatformData* data = reinterpret_cast<ReferencePlatform::PlatformData*>(context.getPlatformData());
    return *((vector<Vec3>*) data->positions);
}

static vector<Vec3>& extractForces(ContextImpl& context) {
    ReferencePlatform::PlatformData* data = reinterpret_cast<ReferencePlatform::PlatformData*>(context.getPlatformData());
    return *((vector<Vec3>*) data->forces);
}

static Vec3* extractBoxVectors(ContextImpl& context) {
    ReferencePlatform::PlatformData* data = reinterpret_cast<ReferencePlatform::PlatformData*>(context.getPlatformData());
    return (Vec3*) data->periodicBoxVectors;
}
```
---
And during `make PythonInstall`, this popped up:
```
Error copying file (if different) from "/srv/public/yaoyic/openmm-torch/python/nnpops.py" to "/srv/public/yaoyic/openmm-torch/build/python/nnpops.py".
```
so I guess this part in file `openmm-torch/python/CMakeLists.txt`:
```CMAKE
COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/nnpops.py" "${CMAKE_CURRENT_BINARY_DIR}/nnpops.py"
```
and this part in file `openmm-torch/python/setup.py` should be removed:
```python
setup(name='nnpops',
      version='1.0',
      py_modules=['nnpops'],
     )
```

After changing the files as has been described, I could `make` the plugin.

**Comment by peastman** [comment]
Thanks!  There was indeed some obsolete code left in the Python build and setup scripts.  I just removed it.

This plugin currently requires you to have the most recent OpenMM code from github.  It doesn't work with 7.4.  That's why you're getting the compilation errors.  I'll see about making it work with older versions.  However, the CUDA platform does require one change to OpenMM in order to work correctly.  That change will be in 7.4.1 (hopefully to be released fairly soon), so that will be the earliest release it's possible to support with this plugin.

**Comment by yaoyic** [comment]
Thanks for the quick response! I will try it out.

**Comment by yaoyic** [comment]
Yes, now it works out smoothly. Thanks!
